var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                     xxx                                                        ",
   "                    xx!xx                                                       ",
   "                    x!!!x                                                       ",
   "                    xx!xx                                                       ",
   "                     xvx                                          xxx           ",
   "               y                                   xx      xx    xx!xx          ",
   "              yyy                   o o      xx                  x!!!x          ",
   "               y                                                 xx!xx          ",
   "                                   xxxxx                          xvx           ",
   "                                                                            xx  ",
   "  x                                       o o        yy                      x  ",
   "  x         yyy         o     yyy                   yyyy                     x  ",
   "  x                          yyyyy       xxxxx       yy                    o x  ",
   "  x                 o         yyy                                            x  ",
   "  x  @                                     s                     xxxxx       x  ",
   "  xxxxxxxxxxxx  xxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxx  xxxxxx!!xxxxxxx  xxxx!!xxx  ",
   "             x!!x             x   x              x  x                           ",
   "             x!!x             x!!!x              x!!x                           ",
   "             x!!x             x!!!x              x!!x                           ",
   "             xxxx             xxxxx              xxxx                           ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                ",
   "                                                                                ",
   "xxxxxxxxxxxxx      xxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxx  xxxxxxxxxxxxxxxxxxx",
   "!!!!!!!!!!!!x      x!!!!!!!!!!!!!!!!x   x!!!!!!!!!!!!!!!!!x  x!!!!!!!!!!!!!!!!!x",
   "xxxxxxxxxxxvx      xvxxxxxxxxxxxxxvxx   xxxvxxxxxxxvxxvxxvx  xvxxvxxxvxxxxvxxxvx",
   "                                                                                ",
   "                                                                                ",
   "                            xx              xx                   xx             ",
   "                                                                         xx     ",
   "                       =                           =    o       xx              ",
   "                      xx                xx              xx                      ",
   "                                                                                ", 
   "                                                                          xx    ",
   "     xx                           =                =       xx                   ",
   "               xx                              o                    xx          ",
   "                                              xx                                ", 
   "                     o             o                     o       xx             ", 
   "                    xx            xx                    xx                xx    ",
   "             xx                            xx                                   ",
   "   @     xx                    o          s                      xx             ", 
   "xxxxxx                        xx         xx         xx                      xx  ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                                                "],
  ["                                                                                ",
   "                                                                                ",
   "xxxxxxxxxxxxx      xxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxx  xxxxxxxxxxxxxxxxxxx",
   "!!!!!!!!!!!!x      x!!!!!!!!!!!!!!!!x   x!!!!!!!!!!!!!!!!!x  x!!!!!!!!!!!!!!!!!x",
   "xxxxxxxxxxxxx      xvxxxxxxxxxxxxxvxx   xxxvxxxxxxxvxxvxxvx  xvxxvxxxvxx",
   "                                                                                ",
   "        xxxxx x  x xxxx xxxx xxxx                         x                      ",
   "        x     x  x x  x x    x                            x       xx             ",
   "        x     xxxx x  x xxxx xxxx                         x               xx     ",
   "        x     x  x x  x    x x                            x      xx              ",
   "        xxxxx x  x xxxx xxxx xxxx                xx       x                      ",
   "                                                          x                      ", 
   "                                                          x                xx    ",
   "                                                          x                      ",
   "                                                          x                      ",
   "                                                          x                      ", 
   "        xxxxx     xxx    xxx     xxxx      xxx    xxxx    x                      ", 
   "   @    x   x     x x    x x     x  x      x x    x  x    x      xx               ",
   "xxxxxx  x   x     x x    x x     x  x      x x    x  x    x                       ",
   "xxxxxx  x   x     x x    x x     x  x      x x    x  x    x                xx     ", 
   "xxxxxx  x   x     x x    x x     x  x      x x    x  x    x   xx                  ",
   "        x   x     x x o  x x     x  x      x x    x  x    x                                  ",
   "        x   x     x x    x x     x  x       x x    x  x    x                                ",
   "        x   x     x x    x x     x  x      x x    x  x    x                                    ",
   "        x   x     x x    x x     x  x      x x    x  x    x                                  ",
   "        x   x     x x    x x     x  x      x x    x  x    x                                  "],
  ["                                                                                                  xxx x       ",
   "                                                                                                      x       ",
   "                                                                                                  xxxxx       ",
   "                                                                                                  x           ",
   "                                                                                                  x xxx       ",
   "                          o                                                                       x x x       ",
   "                                                                                             o o oxxx x       ",
   "                   xxx                                                                                x       ",
   "       !  o  !                                                xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx       ",
   "       x     x                                                x   x x   x x   x x   x x   x x   x x           ",
   "       x= o  x            x                                   xxx x xxx x xxx x xxx x xxx x xxx x xxxxx       ",
   "       x     x                                                  x x   x x   x x   x x   x x   x x     x       ",
   "       !  o  !            o                                  xxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxxxx       ",
   "                                                                                                              ",
   "          o              xxx                              xx                                                  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                      xx                                                      ",
   "                   xxx         xxx                                                                            ",
   "                                                                                                              ",
   "                          o                                                     x      x                      ",
   "                                                          xx     xx                                           ",
   "             xxx         xxx         xxx                                 x                  x                 ",
   "                                                                                                              ",
   "                                                                 ||                                           ",
   "  xxxxxxxxxxx                                                                                                 ",
   "  x         x  o xxxxxxxxx o xxxxxxxxx o xx                                                x                   ",
   "  x         x   x       x   x       x   x                 ||                  x     x                         ",
   "  x  @      xxxxx   o   xxxxx   o   xxxxx                                                                     ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
   "        x=                  =                =x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
